name: Baekjoon Test

on:
  push:
    branches: [main]
    paths:
      - '**.cpp'
      - '**.txt'
      - 'test.sh'
      - '.github/workflows/test.yml'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install g++
      run: sudo apt-get update && sudo apt-get install -y g++

    - name: Run test script
      run: bash ./test.sh

