name: Baekjoon Test

on:
  push:
    paths:
      - '**.cpp'
      - '**.txt'
      - '.github/workflows/test.yml'
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install build tools
      run: sudo apt-get update && sudo apt-get install -y g++

    - name: Run test script
      run: bash ./test.sh
